export type ClaudePracticeQuestion = {
  id: number;
  domain: string;
  select: number;
  en: string;
  zh: string;
  options: Array<[string, string]>;
  answer: number[];
  rationaleEn: string;
  rationaleZh: string;
};

const optionLetters = ["A", "B", "C", "D"];

function renderQuestions(questions: ClaudePracticeQuestion[]) {
  return questions
    .map((question) => {
      const answers = question.answer.map((index) => optionLetters[index]).join(", ");
      const options = question.options
        .map(
          ([en, zh], index) =>
            `${optionLetters[index]}. ${en}  \n   中文：${zh}`,
        )
        .join("\n");

      return `### Q${String(question.id).padStart(2, "0")} · ${question.domain} · Select ${question.select}
**English**  
${question.en}

**中文**  
${question.zh}

${options}

**Answer / 答案：${answers}**

**Rationale (EN):** ${question.rationaleEn}

**解析（中文）：** ${question.rationaleZh}`;
    })
    .join("\n\n");
}

export const officialSampleQuestions: ClaudePracticeQuestion[] = [
  {
    id: 1,
    domain: "Official sample · Domain 3 Integration",
    select: 1,
    en: "A support agent can read tickets, draft replies, issue refunds, and delete accounts, although staff only need the first two capabilities. Which change best applies least privilege?",
    zh: "某客服代理能够读取工单、起草回复、退款和删除账户，但客服人员只需要前两项能力。哪项改动最符合最小权限原则？",
    options: [
      ["Log refund and deletion actions.", "记录退款和删除操作。"],
      ["Remove the refund and deletion tools from the agent configuration.", "从代理配置中移除退款和删除工具。"],
      ["Keep the tools and add a confirmation prompt.", "保留工具并增加确认提示。"],
      ["Use a larger model that follows instructions better.", "改用指令遵循能力更强的大模型。"],
    ],
    answer: [1],
    rationaleEn: "Least privilege removes capabilities that the role does not need. Logging and confirmation are compensating controls, while model size does not define authorization scope.",
    rationaleZh: "最小权限要求直接移除角色不需要的能力。日志和确认属于补偿性控制，模型大小与授权范围无关。",
  },
  {
    id: 2,
    domain: "Official sample · Domain 2 Models, Prompting & Context",
    select: 1,
    en: "Every request repeats the same 8,000-token system prompt and policy, followed by a short changing user message. Which optimization most directly reduces both latency and cost?",
    zh: "每个请求都会重复同一份 8,000 token 的系统提示和策略文档，后面只有很短的动态用户消息。哪项优化最直接降低延迟和成本？",
    options: [
      ["Keep only the first 1,000 policy tokens.", "只保留策略文档前 1,000 个 token。"],
      ["Always choose the smallest model.", "无条件使用最小模型。"],
      ["Put stable content before dynamic content and enable prompt caching.", "把稳定内容放在动态内容之前并启用提示缓存。"],
      ["Move the policy into few-shot examples.", "把策略文档放进少样本示例。"],
    ],
    answer: [2],
    rationaleEn: "A stable prefix can be reused through prompt caching, reducing repeated processing without discarding required policy content.",
    rationaleZh: "提示缓存可以复用稳定前缀，避免每次重复处理，同时不会丢弃必要的策略内容。",
  },
  {
    id: 3,
    domain: "Official sample · Domain 4 Evaluation & Optimization",
    select: 1,
    en: "After a document refresh, a RAG system becomes confidently wrong while latency and the model version stay unchanged. Where should the team investigate first?",
    zh: "文档刷新后，RAG 系统开始自信地给出错误答案，但延迟和模型版本都没有变化。团队首先应该调查哪里？",
    options: [
      ["A silent change to model weights.", "模型权重发生了静默变化。"],
      ["The retrieval and indexing path is returning stale or irrelevant chunks.", "检索与索引链路返回了陈旧或不相关的分块。"],
      ["Temperature is too low.", "temperature 设置过低。"],
      ["The context window became smaller.", "上下文窗口变小了。"],
    ],
    answer: [1],
    rationaleEn: "The failure starts immediately after a corpus refresh, so the highest-value first check is the changed retrieval and indexing path.",
    rationaleZh: "故障紧跟语料刷新出现，因此应优先检查刚发生变化的检索和索引链路。",
  },
];

export const claudePracticeQuestions: ClaudePracticeQuestion[] = [
  {
    id: 1,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "A claims process has fixed steps, deterministic validation rules, and a mandatory approval gate. Which architecture is the best starting point?",
    zh: "理赔流程步骤固定、校验规则确定，并且必须经过审批。最合适的起始架构是什么？",
    options: [
      ["A deterministic workflow with Claude used only where language judgment is needed.", "使用确定性工作流，只在需要语言判断的位置调用 Claude。"],
      ["A fully autonomous agent with every back-office tool.", "配置所有后台工具的全自主代理。"],
      ["A multi-agent swarm with shared memory.", "带共享记忆的多代理群。"],
      ["A single prompt that performs every step.", "用一个提示完成全部步骤。"],
    ],
    answer: [0],
    rationaleEn: "Known steps and approval boundaries favor a workflow. Claude should be inserted only at nondeterministic judgment points.",
    rationaleZh: "固定步骤与审批边界适合工作流；Claude 应只放在需要非确定性判断的节点。",
  },
  {
    id: 2,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "A research task requires planning, choosing sources, adapting after failed searches, and stopping when evidence is sufficient. Which pattern fits best?",
    zh: "一项研究任务需要制定计划、选择来源、在搜索失败后调整策略，并在证据充分时停止。哪种模式最合适？",
    options: [
      ["A fixed linear workflow.", "固定线性工作流。"],
      ["An agentic loop with bounded tools, budget, and stop conditions.", "具有工具边界、预算和停止条件的代理循环。"],
      ["A static RAG lookup only.", "仅使用静态 RAG 查询。"],
      ["A nightly batch job.", "夜间批处理作业。"],
    ],
    answer: [1],
    rationaleEn: "The path cannot be fully predetermined and must adapt to intermediate results, which is the defining need for an agentic pattern.",
    rationaleZh: "执行路径无法预先完全确定，且必须根据中间结果调整，这正是代理模式的适用条件。",
  },
  {
    id: 3,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 2,
    en: "Which TWO capabilities turn a base model call into an augmented LLM system?",
    zh: "以下哪两项能力可以把基础模型调用变成增强型 LLM 系统？（选择两项）",
    options: [
      ["Retrieval over governed enterprise knowledge.", "检索受治理的企业知识。"],
      ["Tool access to live systems.", "通过工具访问实时系统。"],
      ["A larger font in the user interface.", "在用户界面中使用更大的字体。"],
      ["A longer project name.", "使用更长的项目名称。"],
    ],
    answer: [0, 1],
    rationaleEn: "Augmentation adds external context or actions through retrieval, tools, memory, or similar system capabilities.",
    rationaleZh: "增强型 LLM 通过检索、工具、记忆等系统能力获得外部上下文或执行动作。",
  },
  {
    id: 4,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "A complex onboarding task mixes document extraction, policy checks, and personalized explanation. What is the strongest decomposition strategy?",
    zh: "复杂入职任务同时包含文档抽取、策略校验和个性化说明。最稳健的拆分策略是什么？",
    options: [
      ["Ask one prompt to solve everything without intermediate contracts.", "让一个提示一次解决全部问题，不定义中间契约。"],
      ["Separate extraction, deterministic validation, and explanation with typed intermediate outputs.", "把抽取、确定性校验和说明拆开，并定义类型化中间输出。"],
      ["Create one agent for every document field.", "为每个文档字段创建一个代理。"],
      ["Remove validation to reduce latency.", "移除校验以降低延迟。"],
    ],
    answer: [1],
    rationaleEn: "Decomposition should create independently testable stages and explicit contracts, while deterministic checks stay outside the model.",
    rationaleZh: "拆分应形成可独立测试的阶段和明确契约，确定性校验应放在模型之外。",
  },
  {
    id: 5,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 2,
    en: "When is a multi-agent design justified? Select TWO.",
    zh: "在什么情况下多代理设计是合理的？（选择两项）",
    options: [
      ["Specialized tasks require distinct tools and permission boundaries.", "专门任务需要不同工具和权限边界。"],
      ["Parallelizable work can be independently verified before synthesis.", "可并行工作能够在汇总前独立验证。"],
      ["The team wants a more impressive diagram.", "团队希望架构图看起来更复杂。"],
      ["A single model already meets quality, latency, and cost targets.", "单模型已经满足质量、延迟和成本目标。"],
    ],
    answer: [0, 1],
    rationaleEn: "Multi-agent overhead is justified by real specialization, isolation, or parallelism, not by novelty.",
    rationaleZh: "只有真实的专业分工、隔离或并行收益才能抵消多代理的额外复杂度。",
  },
  {
    id: 6,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "Where should an approval gate be placed for an agent that can draft and send contract amendments?",
    zh: "代理能够起草并发送合同修订件。审批门应放在哪里？",
    options: [
      ["After the amendment has been sent.", "修订件发送之后。"],
      ["Immediately before the irreversible send action, with the exact payload visible.", "在不可逆的发送操作之前，并向审批者展示准确载荷。"],
      ["Only during initial user login.", "只在用户初次登录时。"],
      ["Inside the model prompt with no external enforcement.", "仅写进模型提示，不做外部强制。"],
    ],
    answer: [1],
    rationaleEn: "Human approval must govern the actual irreversible action and the exact content, not an earlier abstract intent.",
    rationaleZh: "人工审批必须约束真实的不可逆动作和准确内容，而不是更早的抽象意图。",
  },
  {
    id: 7,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "Which feedback loop best supports continuous improvement without silently changing production behavior?",
    zh: "哪种反馈闭环最能支持持续改进，同时避免生产行为被静默改变？",
    options: [
      ["Collect user feedback, curate it into evaluation cases, test a candidate, then release through a controlled gate.", "收集用户反馈，整理为评测用例，测试候选版本，再通过受控门禁发布。"],
      ["Append every complaint directly to the system prompt.", "把每条投诉直接追加到系统提示。"],
      ["Automatically replace the model after any low rating.", "出现一次低评分就自动更换模型。"],
      ["Ignore feedback until the annual review.", "忽略反馈，等年度评审再处理。"],
    ],
    answer: [0],
    rationaleEn: "A governed loop converts feedback into test evidence before a controlled change reaches production.",
    rationaleZh: "受治理的闭环先把反馈变成测试证据，再让变更经过受控发布。",
  },
  {
    id: 8,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "A stakeholder requests 99.99% answer accuracy but cannot define acceptable errors. What should the architect do first?",
    zh: "利益相关者要求答案准确率达到 99.99%，但无法定义哪些错误可以接受。架构师首先应该做什么？",
    options: [
      ["Promise the target and choose the largest model.", "承诺目标并选择最大模型。"],
      ["Define the task, error taxonomy, measurement method, and risk-weighted acceptance criteria.", "定义任务、错误分类、测量方法和按风险加权的验收标准。"],
      ["Measure only user satisfaction.", "只测用户满意度。"],
      ["Remove all automation.", "移除所有自动化。"],
    ],
    answer: [1],
    rationaleEn: "An SLA is meaningful only after the measured unit, dataset, and severity of errors are explicit.",
    rationaleZh: "只有明确测量单位、数据集和错误严重度，SLA 才具有可执行意义。",
  },
  {
    id: 9,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 2,
    en: "Which TWO changes are normally required when moving a Claude proof of concept to production?",
    zh: "Claude 概念验证进入生产时，通常必须补上哪两项？（选择两项）",
    options: [
      ["A representative evaluation gate and rollback criteria.", "具有代表性的评测门禁和回滚标准。"],
      ["Authentication, authorization, observability, and failure handling around integrations.", "围绕集成补充认证、授权、可观测性和故障处理。"],
      ["A more colorful prototype interface.", "更鲜艳的原型界面。"],
      ["Removal of all operational limits.", "移除全部运行限制。"],
    ],
    answer: [0, 1],
    rationaleEn: "Production readiness adds evidence, controls, operations, and recovery—not merely a polished demonstration.",
    rationaleZh: "生产就绪需要证据、控制、运维和恢复能力，而不仅是更精美的演示。",
  },
  {
    id: 10,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "Two architectures meet current needs. One is easy to change; the other creates a long-lived proprietary dependency. How should the decision process differ?",
    zh: "两个架构都满足当前需求：一个容易更改，另一个会形成长期专有依赖。决策过程应如何区别？",
    options: [
      ["Treat both as equally reversible.", "把两者视为同样可逆。"],
      ["Require stronger evidence and broader review for the hard-to-reverse dependency.", "对难以逆转的依赖要求更强证据和更广泛评审。"],
      ["Always choose the proprietary dependency.", "始终选择专有依赖。"],
      ["Delay every decision indefinitely.", "无限期推迟所有决策。"],
    ],
    answer: [1],
    rationaleEn: "One-way decisions deserve more evidence, explicit exit costs, and wider stakeholder review.",
    rationaleZh: "单向决策需要更多证据、明确退出成本，并扩大相关方评审范围。",
  },
  {
    id: 11,
    domain: "Domain 1 · Solution Design & Architecture",
    select: 1,
    en: "A proposed agent saves 30 seconds per case but adds high review overhead and expensive inference. What is the architect's best next step?",
    zh: "拟议代理每个案例节省 30 秒，但增加大量复核工作和昂贵推理成本。架构师下一步最佳行动是什么？",
    options: [
      ["Approve because automation always creates value.", "批准，因为自动化总能创造价值。"],
      ["Build a total-value model including labor saved, review cost, inference cost, risk, and volume.", "建立总价值模型，纳入节省人工、复核成本、推理成本、风险和业务量。"],
      ["Evaluate only token price.", "只评估 token 价格。"],
      ["Ignore the review process.", "忽略复核流程。"],
    ],
    answer: [1],
    rationaleEn: "Architecture must connect technical design to measurable business value, including hidden operating and risk costs.",
    rationaleZh: "架构必须连接技术方案与可测业务价值，并计入隐藏的运营与风险成本。",
  },
  {
    id: 12,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "A workload has high-volume simple classification and a small number of difficult escalations. What model strategy is strongest?",
    zh: "工作负载包含大量简单分类，以及少量困难升级案例。最优模型策略是什么？",
    options: [
      ["Use the most capable model for every request.", "所有请求都使用能力最强的模型。"],
      ["Route routine cases to a fast, economical model and escalate uncertain cases to a more capable model.", "把常规案例路由到快速经济模型，不确定案例升级到更强模型。"],
      ["Use the smallest model for every request.", "所有请求都使用最小模型。"],
      ["Randomly select a model.", "随机选择模型。"],
    ],
    answer: [1],
    rationaleEn: "Risk- and difficulty-aware routing improves cost and latency while preserving quality on hard cases.",
    rationaleZh: "按风险和难度路由，可降低成本与延迟，同时保留困难案例的质量。",
  },
  {
    id: 13,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 2,
    en: "Which TWO elements belong in a durable system prompt?",
    zh: "以下哪两项适合放进稳定的系统提示？（选择两项）",
    options: [
      ["The role, decision boundaries, and required behavior.", "角色、决策边界和必需行为。"],
      ["The output contract and handling of missing evidence.", "输出契约以及证据缺失时的处理方式。"],
      ["A changing request timestamp inserted at the beginning.", "插在开头且每次变化的请求时间戳。"],
      ["Every possible user document copied permanently.", "永久复制所有可能的用户文档。"],
    ],
    answer: [0, 1],
    rationaleEn: "Stable role, boundaries, and output rules belong in the system layer. Per-request data should remain dynamic and separated.",
    rationaleZh: "稳定角色、边界与输出规则属于系统层；每次请求数据应动态传入并与之分离。",
  },
  {
    id: 14,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "A classifier repeatedly confuses two organization-specific labels. What prompting change is most targeted?",
    zh: "分类器反复混淆两个组织内部标签。最有针对性的提示改进是什么？",
    options: [
      ["Add a few representative positive and boundary examples for both labels.", "为两个标签增加具有代表性的正例和边界例。"],
      ["Repeat the instruction in capital letters.", "用大写字母重复指令。"],
      ["Increase the context with unrelated documents.", "加入无关文档扩充上下文。"],
      ["Remove the label definitions.", "删除标签定义。"],
    ],
    answer: [0],
    rationaleEn: "Few-shot boundary examples teach the intended distinction directly and can be evaluated against the known confusion set.",
    rationaleZh: "少样本边界示例可以直接教给模型预期区分，并能在已知混淆集上验证。",
  },
  {
    id: 15,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "A long prompt contains policies, retrieved evidence, conversation history, and the current task. Responses miss the newest task. What should be done first?",
    zh: "长提示包含策略、检索证据、对话历史和当前任务，但响应经常忽略最新任务。首先应该做什么？",
    options: [
      ["Add more unrelated context.", "添加更多无关上下文。"],
      ["Reorganize context with explicit sections, remove low-value history, and place the current task clearly.", "用明确分区重组上下文，移除低价值历史，并清晰放置当前任务。"],
      ["Increase output tokens only.", "只增加输出 token。"],
      ["Disable all policies.", "禁用所有策略。"],
    ],
    answer: [1],
    rationaleEn: "Context engineering is about relevance, hierarchy, and placement—not simply maximizing token count.",
    rationaleZh: "上下文工程关注相关性、层次和位置，而不是单纯把 token 填满。",
  },
  {
    id: 16,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "What request layout best supports prompt caching?",
    zh: "哪种请求布局最适合提示缓存？",
    options: [
      ["Dynamic timestamps first, stable policy last.", "动态时间戳在前，稳定策略在后。"],
      ["Stable system instructions, tools, and policy first; dynamic user content afterward.", "稳定系统指令、工具和策略在前，动态用户内容在后。"],
      ["Randomize tool order each time.", "每次随机调整工具顺序。"],
      ["Rewrite the policy wording for every call.", "每次调用都改写策略措辞。"],
    ],
    answer: [1],
    rationaleEn: "Caching depends on an identical reusable prefix. Volatile content at the front invalidates the prefix.",
    rationaleZh: "缓存依赖完全一致的可复用前缀；把易变内容放在前面会使缓存失效。",
  },
  {
    id: 17,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 2,
    en: "Which TWO practices improve prompt reuse across a team?",
    zh: "以下哪两项能够改进团队级提示复用？（选择两项）",
    options: [
      ["Version modular prompt components with owners and evaluation coverage.", "对模块化提示组件进行版本管理，明确负责人并覆盖评测。"],
      ["Package repeatable instructions and resources as a governed Skill when appropriate.", "在适合时把可复用指令和资源封装成受治理的 Skill。"],
      ["Let every application copy and edit prompts independently.", "让每个应用独立复制并修改提示。"],
      ["Store production prompts only in personal chat history.", "只把生产提示保存在个人聊天历史中。"],
    ],
    answer: [0, 1],
    rationaleEn: "Reusable prompts need modularity, versioning, ownership, and evidence. Skills can provide progressive disclosure for larger reusable capability packages.",
    rationaleZh: "可复用提示需要模块化、版本、负责人和证据；Skill 可为较大的能力包提供渐进式加载。",
  },
  {
    id: 18,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "A conversation approaches its context limit. Which action is most defensible?",
    zh: "对话接近上下文上限。哪项处理最合理？",
    options: [
      ["Drop the system instructions.", "删除系统指令。"],
      ["Compact older turns into a verified state summary while preserving critical decisions and recent evidence.", "把旧轮次压缩成经过验证的状态摘要，同时保留关键决策和近期证据。"],
      ["Silently remove tool results at random.", "随机静默删除工具结果。"],
      ["Increase temperature.", "提高 temperature。"],
    ],
    answer: [1],
    rationaleEn: "Compaction should preserve task state and critical evidence while removing redundant conversational detail.",
    rationaleZh: "上下文压缩应保留任务状态和关键证据，同时去除冗余对话细节。",
  },
  {
    id: 19,
    domain: "Domain 2 · Claude Models, Prompting & Context Engineering",
    select: 1,
    en: "A high-stakes analysis needs deeper reasoning, but users only need the conclusion and evidence. What is the best design?",
    zh: "高风险分析需要更深入的推理，但用户只需要结论和证据。最佳设计是什么？",
    options: [
      ["Require the model to expose every hidden reasoning token.", "要求模型暴露所有隐藏推理 token。"],
      ["Allocate appropriate reasoning effort and request a concise decision, assumptions, and verifiable evidence.", "配置适当推理强度，并要求输出简洁决策、假设和可验证证据。"],
      ["Disable evaluation because reasoning is enabled.", "因为启用了推理而取消评测。"],
      ["Use chain-of-thought text as the only audit log.", "把思维链文本作为唯一审计日志。"],
    ],
    answer: [1],
    rationaleEn: "The system should optimize internal reasoning while exposing decision-relevant evidence, not depend on private reasoning traces as an audit mechanism.",
    rationaleZh: "系统应优化内部推理并输出与决策相关的证据，而不应把私有推理轨迹当作审计机制。",
  },
  {
    id: 20,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "An agent is configured with 140 tools, but one role uses only six. What is the best first change?",
    zh: "代理配置了 140 个工具，但某角色只使用其中 6 个。最佳第一步是什么？",
    options: [
      ["Increase the context window.", "增大上下文窗口。"],
      ["Expose only the six required tools and discover additional tools progressively when authorized.", "只暴露 6 个必需工具，并在授权后渐进发现其他工具。"],
      ["Rename every tool.", "重命名全部工具。"],
      ["Use a larger model.", "使用更大的模型。"],
    ],
    answer: [1],
    rationaleEn: "Reducing capability bloat improves security, tool selection accuracy, context efficiency, and operability.",
    rationaleZh: "减少能力膨胀可以同时提升安全性、工具选择准确性、上下文效率和可运维性。",
  },
  {
    id: 21,
    domain: "Domain 3 · Integration",
    select: 2,
    en: "Which TWO controls are required when a tool reads customer records?",
    zh: "工具读取客户记录时必须具备哪两项控制？（选择两项）",
    options: [
      ["Authenticate the calling workload or user.", "认证调用工作负载或用户身份。"],
      ["Authorize access at the resource and action level using the effective identity.", "基于实际生效身份在资源和动作层授权。"],
      ["Trust the model to infer permissions from the prompt.", "相信模型从提示中推断权限。"],
      ["Return all fields to simplify implementation.", "返回所有字段以简化实现。"],
    ],
    answer: [0, 1],
    rationaleEn: "Authentication proves identity; authorization enforces what that identity may do. Both belong outside model judgment.",
    rationaleZh: "认证证明身份，授权限制该身份可以做什么；两者都必须由模型外部机制强制执行。",
  },
  {
    id: 22,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "A live price lookup is accurate but adds 1.8 seconds to every answer. Most questions do not need current prices. What design best balances accuracy and latency?",
    zh: "实时价格查询准确，但每个回答增加 1.8 秒；大多数问题并不需要当前价格。哪种设计最能平衡准确性和延迟？",
    options: [
      ["Call the price tool on every request.", "每个请求都调用价格工具。"],
      ["Route only freshness-sensitive intents to the price tool and measure fallback behavior.", "只把需要新鲜数据的意图路由到价格工具，并测量回退行为。"],
      ["Cache prices forever.", "永久缓存价格。"],
      ["Remove all price information.", "移除全部价格信息。"],
    ],
    answer: [1],
    rationaleEn: "Selective tool routing spends latency only where freshness materially changes correctness.",
    rationaleZh: "选择性工具路由只在新鲜度会实质影响正确性时支付延迟成本。",
  },
  {
    id: 23,
    domain: "Domain 3 · Integration",
    select: 2,
    en: "Which TWO observability fields are most important for tracing a failed multi-tool request?",
    zh: "追踪一次多工具请求失败时，哪两类可观测字段最重要？（选择两项）",
    options: [
      ["A correlation or trace ID propagated across model and tool calls.", "贯穿模型和工具调用的关联 ID 或 trace ID。"],
      ["Structured records of tool name, latency, status, retry, and sanitized error category.", "工具名、延迟、状态、重试和脱敏错误类别的结构化记录。"],
      ["The user's screen resolution.", "用户屏幕分辨率。"],
      ["The color of the submit button.", "提交按钮颜色。"],
    ],
    answer: [0, 1],
    rationaleEn: "Cross-boundary correlation and structured event details let operators reconstruct causality without logging sensitive payloads.",
    rationaleZh: "跨边界关联与结构化事件细节能够重建因果链，同时避免记录敏感载荷。",
  },
  {
    id: 24,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "Policies contain short numbered clauses and cross-references. Which chunking strategy is the strongest starting point?",
    zh: "策略文档由短编号条款和交叉引用组成。最合适的初始分块策略是什么？",
    options: [
      ["Split at arbitrary fixed characters with no overlap or metadata.", "按固定字符任意切分，不保留重叠或元数据。"],
      ["Chunk by semantic clause boundaries, preserve section metadata, and include limited neighboring context.", "按语义条款边界切分，保留章节元数据，并加入有限相邻上下文。"],
      ["Store the entire corpus as one chunk.", "把整个语料库存成一个分块。"],
      ["Index only document titles.", "只索引文档标题。"],
    ],
    answer: [1],
    rationaleEn: "Chunking should match document structure and retrieval needs while preserving provenance and nearby dependencies.",
    rationaleZh: "分块应匹配文档结构和检索需求，并保留来源与相邻依赖信息。",
  },
  {
    id: 25,
    domain: "Domain 3 · Integration",
    select: 2,
    en: "Which TWO metadata fields most improve governed retrieval over versioned procedures?",
    zh: "对版本化流程文档进行受治理检索时，哪两类元数据最有价值？（选择两项）",
    options: [
      ["Effective date and superseded status.", "生效日期与是否被替代。"],
      ["Business unit, jurisdiction, and access classification.", "业务部门、适用法域和访问分类。"],
      ["Random ingestion order.", "随机摄取顺序。"],
      ["The file icon color.", "文件图标颜色。"],
    ],
    answer: [0, 1],
    rationaleEn: "Version, applicability, and access metadata let retrieval filter for current and authorized evidence.",
    rationaleZh: "版本、适用范围和访问元数据使检索能够过滤出当前有效且已授权的证据。",
  },
  {
    id: 26,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "Users search by exact product codes and by natural-language symptoms. Which retrieval design is strongest?",
    zh: "用户既会按精确产品代码搜索，也会按自然语言症状搜索。最合适的检索设计是什么？",
    options: [
      ["Vector search only.", "只用向量检索。"],
      ["Keyword plus semantic retrieval, followed by reranking and metadata filters.", "关键词与语义混合检索，再进行重排和元数据过滤。"],
      ["Alphabetical document order.", "按文档字母顺序。"],
      ["Always return the newest document regardless of relevance.", "不考虑相关性，始终返回最新文档。"],
    ],
    answer: [1],
    rationaleEn: "Hybrid retrieval covers lexical identifiers and semantic meaning; reranking and filters improve precision.",
    rationaleZh: "混合检索同时覆盖精确标识和语义含义，重排与过滤进一步提升精度。",
  },
  {
    id: 27,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "Several Claude applications must use the same standardized enterprise tools and resources. Which mechanism best reduces bespoke integration work?",
    zh: "多个 Claude 应用需要使用同一套标准化企业工具与资源。哪种机制最能减少定制集成工作？",
    options: [
      ["A governed MCP server with explicit tool schemas and authorization.", "具有明确工具 schema 和授权控制的受治理 MCP 服务器。"],
      ["Copy database passwords into every system prompt.", "把数据库密码复制进每个系统提示。"],
      ["One-off screen scraping in each application.", "每个应用单独做页面抓取。"],
      ["A shared spreadsheet with manual execution.", "共享表格加人工执行。"],
    ],
    answer: [0],
    rationaleEn: "MCP standardizes discovery and invocation across compatible clients, but still requires explicit trust and authorization controls.",
    rationaleZh: "MCP 可以在兼容客户端之间标准化发现和调用，但仍必须明确建立信任与授权控制。",
  },
  {
    id: 28,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "A deterministic deployment pipeline must invoke Claude-related configuration as part of CI. Which interface is usually the best fit?",
    zh: "确定性的部署流水线需要在 CI 中调用 Claude 相关配置。通常哪种接口最合适？",
    options: [
      ["An interactive chat window.", "交互式聊天窗口。"],
      ["A versioned CLI or API command with machine-readable output and exit codes.", "具有版本控制、机器可读输出和退出码的 CLI 或 API 命令。"],
      ["A human copying text between systems.", "人工在系统间复制文本。"],
      ["An unconstrained autonomous agent.", "不受约束的自主代理。"],
    ],
    answer: [1],
    rationaleEn: "CI needs deterministic, scriptable, observable interfaces rather than conversational interaction.",
    rationaleZh: "CI 需要确定、可脚本化、可观测的接口，而不是对话式交互。",
  },
  {
    id: 29,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "Two independently operated agents need to exchange delegated tasks and results. What is the first architectural requirement?",
    zh: "两个独立运维的代理需要交换委派任务和结果。首要架构要求是什么？",
    options: [
      ["A clear agent-to-agent contract for identity, task schema, status, timeout, and result provenance.", "针对身份、任务 schema、状态、超时和结果来源建立清晰的 agent-to-agent 契约。"],
      ["A shared unrestricted administrator token.", "共享不受限制的管理员 token。"],
      ["Identical model versions only.", "必须使用完全相同的模型版本。"],
      ["No failure states.", "不定义失败状态。"],
    ],
    answer: [0],
    rationaleEn: "Agent-to-agent integration needs an explicit protocol and trust boundary before implementation details.",
    rationaleZh: "代理间集成首先要定义明确协议和信任边界，再讨论实现细节。",
  },
  {
    id: 30,
    domain: "Domain 3 · Integration",
    select: 1,
    en: "A platform has thousands of rarely used tools. Which context strategy is most scalable?",
    zh: "平台有数千个很少使用的工具。哪种上下文策略最具扩展性？",
    options: [
      ["Load every tool definition into every request.", "每个请求都加载全部工具定义。"],
      ["Use progressive discovery or tool search, then load only the authorized relevant tools.", "使用渐进式发现或工具搜索，只加载已授权且相关的工具。"],
      ["Remove tool descriptions.", "删除工具描述。"],
      ["Compress all tools into one ambiguous tool.", "把所有工具压缩成一个模糊工具。"],
    ],
    answer: [1],
    rationaleEn: "Progressive discovery reduces context cost and selection ambiguity while preserving a large capability catalog.",
    rationaleZh: "渐进式发现既能保留大规模能力目录，又能减少上下文成本与选择歧义。",
  },
  {
    id: 31,
    domain: "Domain 3 · Integration",
    select: 2,
    en: "Which TWO risks increase when all tools, policies, and documents are loaded monolithically into every request?",
    zh: "把全部工具、策略和文档整体加载到每个请求，会增加哪两类风险？（选择两项）",
    options: [
      ["Higher token cost and latency.", "更高 token 成本和延迟。"],
      ["More irrelevant context and tool-selection confusion.", "更多无关上下文和工具选择混淆。"],
      ["Improved least privilege by default.", "默认改善最小权限。"],
      ["Guaranteed factual accuracy.", "保证事实准确性。"],
    ],
    answer: [0, 1],
    rationaleEn: "Monolithic context consumes tokens and expands the model's decision surface without guaranteeing relevance or authorization.",
    rationaleZh: "整体上下文会消耗 token 并扩大模型决策面，却不能保证相关性或授权正确。",
  },
  {
    id: 32,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 2,
    en: "Which TWO properties make a production success criterion useful?",
    zh: "生产成功标准需要具备哪两项属性？（选择两项）",
    options: [
      ["It is measurable on a defined dataset or traffic slice.", "能够在明确数据集或流量切片上测量。"],
      ["It includes a target and an unacceptable threshold tied to business risk.", "包含与业务风险相关的目标值和不可接受阈值。"],
      ["It uses the phrase high quality.", "使用“高质量”这个词。"],
      ["It changes after every test result.", "每次测试后都改变标准。"],
    ],
    answer: [0, 1],
    rationaleEn: "Useful criteria define how, where, and against what threshold performance is judged.",
    rationaleZh: "有效标准必须说明如何测、在哪测，以及以什么阈值判断。",
  },
  {
    id: 33,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "What is the best source for a regression evaluation dataset?",
    zh: "回归评测数据集的最佳来源是什么？",
    options: [
      ["Only easy synthetic examples.", "只有简单合成样例。"],
      ["Representative production-like cases, known failures, edge cases, and risk-weighted adversarial cases with reviewed labels.", "具有代表性的类生产案例、已知故障、边界案例和按风险加权的对抗案例，并经过标签复核。"],
      ["The prompt author's favorite examples.", "提示作者最喜欢的例子。"],
      ["A random web corpus with no labels.", "没有标签的随机网页语料。"],
    ],
    answer: [1],
    rationaleEn: "A useful dataset reflects actual task distribution and costly failure modes, with trustworthy expected outcomes.",
    rationaleZh: "有效数据集应反映真实任务分布和高代价故障模式，并拥有可信预期结果。",
  },
  {
    id: 34,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 2,
    en: "Which TWO evaluators should be combined for a customer-service answer?",
    zh: "评测客服回答时，哪两类评估器应该组合使用？（选择两项）",
    options: [
      ["Deterministic checks for schema, citations, and prohibited commitments.", "针对 schema、引用和禁止承诺的确定性检查。"],
      ["Human or rubric-based model grading for helpfulness and nuanced correctness.", "由人工或基于 rubric 的模型评分评估帮助性和细微正确性。"],
      ["Only response length.", "只看响应长度。"],
      ["Only token cost.", "只看 token 成本。"],
    ],
    answer: [0, 1],
    rationaleEn: "Mixed methodologies use deterministic checks where possible and judgment-based evaluation where semantics require it.",
    rationaleZh: "混合方法在可确定的位置使用规则检查，在需要语义判断的位置使用人工或 rubric 评分。",
  },
  {
    id: 35,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "What is required before an online A/B test of a new prompt?",
    zh: "对新提示做线上 A/B 测试前，必须具备什么？",
    options: [
      ["A predefined hypothesis, primary metric, guardrail metrics, traffic allocation, and stop rule.", "预先定义假设、主指标、护栏指标、流量分配和停止规则。"],
      ["A promise that the new prompt is better.", "承诺新提示一定更好。"],
      ["No rollback path.", "不需要回滚路径。"],
      ["A different model for every user.", "每个用户使用不同模型。"],
    ],
    answer: [0],
    rationaleEn: "Pre-registration prevents metric shopping and protects users through explicit guardrails and stopping conditions.",
    rationaleZh: "预先定义可避免事后挑指标，并通过护栏和停止条件保护用户。",
  },
  {
    id: 36,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "A model follows the requested format but invents unsupported facts. What failure category is most accurate?",
    zh: "模型遵循了请求格式，却编造了没有证据支持的事实。最准确的故障分类是什么？",
    options: [
      ["Transport timeout.", "传输超时。"],
      ["Grounding or hallucination failure.", "事实依据或幻觉故障。"],
      ["Authentication failure.", "认证失败。"],
      ["CSS regression.", "CSS 回归。"],
    ],
    answer: [1],
    rationaleEn: "Format compliance is separate from factual grounding. Diagnosis should target evidence use, retrieval, and unsupported-claim controls.",
    rationaleZh: "格式合规与事实依据是不同维度；应针对证据使用、检索和无依据声明控制进行诊断。",
  },
  {
    id: 37,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "An answer-quality regression appears only for one product family after an index rebuild. What should be compared first?",
    zh: "索引重建后，只有一个产品系列出现回答质量回归。首先应该比较什么？",
    options: [
      ["Retrieved chunk relevance, metadata filters, embedding/index versions, and coverage before versus after the rebuild.", "比较重建前后的检索分块相关性、元数据过滤、embedding/索引版本和覆盖率。"],
      ["The user interface theme.", "用户界面主题。"],
      ["The model vendor's stock price.", "模型供应商股价。"],
      ["Only output token count.", "只比较输出 token 数。"],
    ],
    answer: [0],
    rationaleEn: "The change is localized to the rebuilt retrieval path and one corpus segment, so retrieval evidence has the highest diagnostic value.",
    rationaleZh: "变化集中在重建的检索链路和特定语料分区，因此检索证据的诊断价值最高。",
  },
  {
    id: 38,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 2,
    en: "Which TWO optimizations can reduce cost without automatically lowering answer quality?",
    zh: "以下哪两项优化可以降低成本，又不会自动牺牲回答质量？（选择两项）",
    options: [
      ["Cache stable prompt prefixes and reused tool definitions.", "缓存稳定提示前缀和重复使用的工具定义。"],
      ["Route simple cases to a cheaper model while retaining evaluation-based escalation.", "把简单案例路由到更经济的模型，同时保留基于评测的升级机制。"],
      ["Delete required policy context.", "删除必需策略上下文。"],
      ["Stop monitoring failures.", "停止监控故障。"],
    ],
    answer: [0, 1],
    rationaleEn: "Caching removes repeated processing, and routing allocates capability by need; both should be validated by evals.",
    rationaleZh: "缓存消除重复处理，路由按需求分配模型能力；两者都应通过评测验证。",
  },
  {
    id: 39,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 2,
    en: "Which TWO metric groups are required to operate an agentic system?",
    zh: "运维代理系统时必须具备哪两组指标？（选择两项）",
    options: [
      ["Outcome quality, safety violations, and human escalation rate.", "结果质量、安全违规和人工升级率。"],
      ["End-to-end latency, tool latency/error rate, token usage, and cost.", "端到端延迟、工具延迟/错误率、token 用量和成本。"],
      ["Number of marketing slogans.", "营销口号数量。"],
      ["Office seating capacity.", "办公室座位容量。"],
    ],
    answer: [0, 1],
    rationaleEn: "Operations need both user/business outcomes and component/resource signals; either alone leaves blind spots.",
    rationaleZh: "运维既需要用户与业务结果，也需要组件和资源信号；缺少任何一组都会形成盲点。",
  },
  {
    id: 40,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "A more capable model improves accuracy by 0.3 percentage points but doubles latency and triples cost. What should decide adoption?",
    zh: "更强模型把准确率提高 0.3 个百分点，但延迟翻倍、成本增至三倍。是否采用应由什么决定？",
    options: [
      ["Model reputation alone.", "只看模型声誉。"],
      ["Whether the measured quality gain exceeds risk-weighted thresholds and the latency/cost budget on representative traffic.", "在代表性流量上，测得的质量收益是否超过按风险加权的阈值，并符合延迟与成本预算。"],
      ["Always use the newest model.", "始终使用最新模型。"],
      ["The preference of one developer.", "某个开发者的偏好。"],
    ],
    answer: [1],
    rationaleEn: "Optimization is multi-objective; adoption follows pre-agreed quality, risk, latency, and cost criteria.",
    rationaleZh: "优化是多目标问题；采用决策必须依据预先约定的质量、风险、延迟和成本标准。",
  },
  {
    id: 41,
    domain: "Domain 4 · Evaluation, Testing & Optimization",
    select: 1,
    en: "What is the safest gate for a model or architecture migration?",
    zh: "模型或架构迁移最安全的门禁是什么？",
    options: [
      ["A successful API call.", "API 调用成功。"],
      ["Passing versioned regression suites, safety thresholds, performance budgets, canary criteria, and rollback readiness.", "通过版本化回归套件、安全阈值、性能预算、金丝雀标准，并具备回滚准备。"],
      ["A new model announcement.", "新模型发布公告。"],
      ["No user complaints during one minute.", "一分钟内没有用户投诉。"],
    ],
    answer: [1],
    rationaleEn: "A migration gate must prove behavior and operational safety, not just connectivity.",
    rationaleZh: "迁移门禁必须证明行为和运行安全，而不仅是连通性。",
  },
  {
    id: 42,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 1,
    en: "Where should direct jailbreak screening occur?",
    zh: "针对直接越狱攻击的筛查应放在哪里？",
    options: [
      ["Before untrusted user input reaches the main privileged workflow.", "在不可信用户输入进入主特权工作流之前。"],
      ["Only after a side effect completes.", "只在副作用完成后。"],
      ["Inside a dashboard viewed monthly.", "放在每月查看的看板中。"],
      ["Nowhere if a large model is used.", "如果使用大模型则无需筛查。"],
    ],
    answer: [0],
    rationaleEn: "Input screening reduces malicious instructions before they reach higher-value context, tools, or actions.",
    rationaleZh: "输入筛查应在恶意指令接触高价值上下文、工具或动作前进行。",
  },
  {
    id: 43,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 2,
    en: "Which TWO output controls are appropriate for a regulated advice assistant?",
    zh: "受监管建议助手适合采用哪两项输出控制？（选择两项）",
    options: [
      ["Validate required citations and prohibit unsupported claims before display.", "展示前验证必需引用并禁止无依据声明。"],
      ["Route high-risk recommendations to qualified human review.", "把高风险建议路由到具备资质的人工审核。"],
      ["Hide every refusal from monitoring.", "从监控中隐藏所有拒绝。"],
      ["Allow the model to approve its own policy exceptions.", "允许模型自行批准策略例外。"],
    ],
    answer: [0, 1],
    rationaleEn: "Output validation and qualified review address unsupported or high-consequence recommendations before users act on them.",
    rationaleZh: "输出验证和合格人工审核能在用户采取行动前拦截无依据或高后果建议。",
  },
  {
    id: 44,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 1,
    en: "How should authorization be enforced for a tool that transfers funds?",
    zh: "资金转账工具的授权应如何强制？",
    options: [
      ["The prompt should ask the model to be careful.", "在提示中要求模型谨慎。"],
      ["A deterministic policy layer must verify identity, scope, limits, and approval immediately before execution.", "确定性策略层必须在执行前验证身份、权限范围、限额和审批。"],
      ["The tool should accept any model-generated amount.", "工具接受模型生成的任意金额。"],
      ["Only log transfers afterward.", "只在转账后记录日志。"],
    ],
    answer: [1],
    rationaleEn: "High-impact authorization is an external policy decision and must not depend on model compliance.",
    rationaleZh: "高影响授权属于模型外部策略决策，不能依赖模型自觉遵守。",
  },
  {
    id: 45,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 1,
    en: "A policy service is unavailable while an agent requests a destructive action. What should a fail-closed design do?",
    zh: "策略服务不可用时，代理请求执行破坏性操作。失败关闭设计应如何处理？",
    options: [
      ["Allow the action to preserve availability.", "允许操作以保持可用性。"],
      ["Deny or pause the action and surface a recoverable review path.", "拒绝或暂停操作，并提供可恢复的审核路径。"],
      ["Guess the missing policy.", "猜测缺失策略。"],
      ["Retry forever.", "无限重试。"],
    ],
    answer: [1],
    rationaleEn: "When the safety decision cannot be made, high-impact actions should not proceed.",
    rationaleZh: "无法作出安全判断时，高影响动作不得继续执行。",
  },
  {
    id: 46,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 2,
    en: "Which TWO factors should determine whether a decision needs human review?",
    zh: "是否需要人工审核，应重点考虑哪两项因素？（选择两项）",
    options: [
      ["Consequence and reversibility of the action.", "动作后果与可逆性。"],
      ["Model confidence plus the quality of supporting evidence.", "模型置信度以及支持证据的质量。"],
      ["The day of the week only.", "只看星期几。"],
      ["The model's marketing tier.", "模型的营销级别。"],
    ],
    answer: [0, 1],
    rationaleEn: "Review routing should combine decision impact with uncertainty and evidence, rather than a single arbitrary threshold.",
    rationaleZh: "审核路由应综合决策影响、不确定性和证据，而不是依赖单一任意阈值。",
  },
  {
    id: 47,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 2,
    en: "Which TWO controls directly support GDPR-aligned design for a Claude application?",
    zh: "以下哪两项控制直接支持 Claude 应用符合 GDPR 的设计？（选择两项）",
    options: [
      ["Data minimization and purpose limitation.", "数据最小化与目的限制。"],
      ["Documented retention, deletion, access, and data-subject request handling.", "明确留存、删除、访问和数据主体请求处理。"],
      ["Collect every field in case it becomes useful.", "收集所有字段以备将来使用。"],
      ["Keep logs forever without classification.", "不做分类，永久保存日志。"],
    ],
    answer: [0, 1],
    rationaleEn: "Privacy architecture starts with limiting collection and defining lifecycle and rights controls for personal data.",
    rationaleZh: "隐私架构首先要限制数据收集，并为个人数据定义生命周期和权利处理控制。",
  },
  {
    id: 48,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 1,
    en: "A healthcare assistant processes protected health information. What is the strongest architectural response?",
    zh: "医疗助手处理受保护健康信息。最稳健的架构响应是什么？",
    options: [
      ["Assume encryption alone is sufficient.", "假设只要加密就足够。"],
      ["Confirm the permitted service and contractual boundary, minimize PHI, enforce access controls, audit use, and validate retention requirements.", "确认允许使用的服务与合同边界，最小化 PHI，强制访问控制，审计使用，并验证留存要求。"],
      ["Send PHI to every debugging log.", "把 PHI 写入所有调试日志。"],
      ["Use a public shared account.", "使用公开共享账户。"],
    ],
    answer: [1],
    rationaleEn: "Regulated data requires end-to-end contractual, technical, operational, and lifecycle controls—not a single safeguard.",
    rationaleZh: "受监管数据需要合同、技术、运营和生命周期的端到端控制，而不是单一防护。",
  },
  {
    id: 49,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 1,
    en: "A government workload requires FedRAMP-aligned operation. What should the architect verify first?",
    zh: "政府工作负载要求符合 FedRAMP。架构师首先应验证什么？",
    options: [
      ["That the exact service, region, data flow, and supporting components fall within the authorized boundary.", "准确服务、区域、数据流和支撑组件是否处于授权边界内。"],
      ["That the user interface uses government colors.", "界面是否使用政府风格颜色。"],
      ["That the model is the newest release.", "模型是否为最新版本。"],
      ["That developers prefer the platform.", "开发者是否喜欢该平台。"],
    ],
    answer: [0],
    rationaleEn: "Compliance attaches to a defined authorization boundary and configuration, not to a product name in the abstract.",
    rationaleZh: "合规依附于明确的授权边界和配置，而不是抽象的产品名称。",
  },
  {
    id: 50,
    domain: "Domain 5 · Governance, Safety & Risk Management",
    select: 2,
    en: "Which TWO practices address fairness and transparency for an AI-assisted eligibility decision?",
    zh: "AI 辅助资格判断中，哪两项实践可以应对公平性与透明度问题？（选择两项）",
    options: [
      ["Evaluate error rates across relevant groups and investigate material disparities.", "按相关群体评测错误率并调查重大差异。"],
      ["Disclose AI involvement, provide decision evidence, and preserve an appeal or human review path.", "披露 AI 参与，提供决策证据，并保留申诉或人工复核路径。"],
      ["Hide the criteria to prevent questions.", "隐藏标准以避免质疑。"],
      ["Optimize only aggregate accuracy.", "只优化总体准确率。"],
    ],
    answer: [0, 1],
    rationaleEn: "Aggregate performance can hide group harm; transparency and recourse are part of responsible decision design.",
    rationaleZh: "总体性能可能掩盖群体伤害；透明与救济机制也是负责任决策设计的一部分。",
  },
  {
    id: 51,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "What is the best first output from a discovery workshop?",
    zh: "需求发现工作坊最重要的第一项产出是什么？",
    options: [
      ["A named model choice before requirements are known.", "在需求明确前先指定模型。"],
      ["A problem statement with users, current workflow, desired outcomes, constraints, risks, and measurable success criteria.", "包含用户、当前流程、期望结果、约束、风险和可测成功标准的问题陈述。"],
      ["A final production architecture.", "最终生产架构。"],
      ["A list of fashionable AI terms.", "一组流行 AI 术语。"],
    ],
    answer: [1],
    rationaleEn: "Discovery should establish the decision context before selecting technology.",
    rationaleZh: "需求发现应先建立决策上下文，再选择技术。",
  },
  {
    id: 52,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "How should an architect present two viable options to executives?",
    zh: "架构师应如何向管理层呈现两个可行选项？",
    options: [
      ["Describe technical components without a recommendation.", "只描述技术组件，不给建议。"],
      ["Compare business outcome, risk, cost, time, reversibility, and evidence, then recommend one with conditions.", "比较业务结果、风险、成本、时间、可逆性和证据，并提出带条件的建议。"],
      ["Present the favorite option as risk-free.", "把偏好的选项说成没有风险。"],
      ["Hide rejected alternatives.", "隐藏被拒绝的替代方案。"],
    ],
    answer: [1],
    rationaleEn: "Decision-ready communication makes trade-offs and recommendation conditions explicit in stakeholder terms.",
    rationaleZh: "可决策沟通要用利益相关者能行动的语言明确权衡和建议条件。",
  },
  {
    id: 53,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "A sponsor expects the pilot's demo accuracy to transfer directly to all production traffic. What should the architect do?",
    zh: "发起人认为试点演示的准确率会直接复制到全部生产流量。架构师应如何处理？",
    options: [
      ["Confirm the expectation to maintain momentum.", "确认该预期以保持推进速度。"],
      ["Explain dataset and operating differences, define validation gaps, and agree on staged acceptance criteria.", "解释数据集与运行条件差异，明确验证缺口，并约定分阶段验收标准。"],
      ["Avoid discussing limitations.", "避免讨论限制。"],
      ["Replace the evaluation dataset with demo cases.", "用演示案例替换评测数据集。"],
    ],
    answer: [1],
    rationaleEn: "Expectation alignment distinguishes demonstrated evidence from assumptions and turns gaps into explicit acceptance work.",
    rationaleZh: "预期对齐要区分已证明证据与假设，并把缺口转成明确验收工作。",
  },
  {
    id: 54,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 2,
    en: "Which TWO elements belong in an AI service-level agreement?",
    zh: "AI 服务级别协议中应包含哪两类内容？（选择两项）",
    options: [
      ["Operational measures such as availability, latency, throughput, and recovery.", "可用性、延迟、吞吐和恢复等运行指标。"],
      ["Quality and safety measures with evaluation scope, thresholds, escalation, and review cadence.", "包含评测范围、阈值、升级和复核频率的质量与安全指标。"],
      ["A claim that answers are always correct.", "声称回答永远正确。"],
      ["Only the monthly API bill.", "只写每月 API 账单。"],
    ],
    answer: [0, 1],
    rationaleEn: "AI SLAs must cover traditional operations plus model-dependent quality and safety behavior.",
    rationaleZh: "AI SLA 既要覆盖传统运维指标，也要覆盖模型相关的质量和安全行为。",
  },
  {
    id: 55,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "Which artifact best records why an integration protocol was chosen over alternatives?",
    zh: "哪种文档最适合记录为何选择某个集成协议而放弃其他方案？",
    options: [
      ["An architecture decision record with context, options, decision, consequences, and review trigger.", "包含上下文、选项、决策、后果和复核触发条件的架构决策记录。"],
      ["A chat message saying decided.", "一条写着“已决定”的聊天消息。"],
      ["Only a network diagram.", "只有网络图。"],
      ["An undocumented code comment.", "未纳入文档的代码注释。"],
    ],
    answer: [0],
    rationaleEn: "An ADR preserves decision intent and consequences so future teams can evaluate whether assumptions still hold.",
    rationaleZh: "ADR 保留决策意图和后果，使未来团队能判断原有假设是否仍成立。",
  },
  {
    id: 56,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 2,
    en: "Which TWO deliverables make a production handoff resilient?",
    zh: "哪两项交付物能让生产移交更可靠？（选择两项）",
    options: [
      ["Runbooks with owners, alerts, failure modes, recovery steps, and escalation paths.", "包含负责人、告警、故障模式、恢复步骤和升级路径的运行手册。"],
      ["Versioned architecture, configuration, evaluation baselines, known limits, and decision records.", "版本化架构、配置、评测基线、已知限制和决策记录。"],
      ["The architect's personal memory.", "架构师个人记忆。"],
      ["A single screenshot of the demo.", "一张演示截图。"],
    ],
    answer: [0, 1],
    rationaleEn: "Handoff must transfer operational action and design intent, not just implementation files.",
    rationaleZh: "移交必须传递运维行动和设计意图，而不仅是实现文件。",
  },
  {
    id: 57,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "Which lifecycle sequence is most defensible for a new Claude solution?",
    zh: "新 Claude 解决方案最合理的生命周期顺序是什么？",
    options: [
      ["Build → announce → discover requirements → monitor.", "构建→宣布→发现需求→监控。"],
      ["Discover → define success → design → prototype → evaluate → productionize → monitor → iterate.", "发现→定义成功→设计→原型→评测→生产化→监控→迭代。"],
      ["Choose model → skip evaluation → deploy globally.", "选择模型→跳过评测→全球部署。"],
      ["Prototype forever.", "永远停留在原型。"],
    ],
    answer: [1],
    rationaleEn: "The sequence creates evidence before scaling and keeps monitoring and iteration inside the lifecycle.",
    rationaleZh: "该顺序先产生证据再扩大规模，并把监控与迭代纳入生命周期。",
  },
  {
    id: 58,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "How should conflicting stakeholder feedback be handled?",
    zh: "应如何处理相互冲突的利益相关者反馈？",
    options: [
      ["Implement the loudest request.", "实现声音最大的请求。"],
      ["Map feedback to user segments, objectives, risk, evidence, and decision ownership, then resolve through explicit priorities.", "把反馈映射到用户群、目标、风险、证据和决策归属，再通过明确优先级解决。"],
      ["Average every request into one design.", "把所有要求平均成一个设计。"],
      ["Ignore all feedback.", "忽略全部反馈。"],
    ],
    answer: [1],
    rationaleEn: "Structured feedback management separates preference from evidence and clarifies who decides under competing objectives.",
    rationaleZh: "结构化反馈管理能区分偏好与证据，并明确目标冲突时由谁决策。",
  },
  {
    id: 59,
    domain: "Domain 6 · Stakeholder Communication & Lifecycle Management",
    select: 1,
    en: "A pilot misses its quality target but shows strong time savings. What is the best executive update?",
    zh: "试点没有达到质量目标，但节省时间效果明显。最佳管理层更新是什么？",
    options: [
      ["The pilot was successful.", "试点成功。"],
      ["State both results, quantify the gap and value, explain the leading cause, and recommend a bounded next experiment with a decision date.", "同时说明两项结果，量化差距与价值，解释主要原因，并建议有边界的下一轮实验和决策日期。"],
      ["Hide the failed metric.", "隐藏失败指标。"],
      ["Declare the technology unusable.", "宣布该技术不可用。"],
    ],
    answer: [1],
    rationaleEn: "Senior communication preserves the mixed evidence and converts it into a decision-ready next step.",
    rationaleZh: "高级沟通应保留混合证据，并将其转化为可决策的下一步。",
  },
  {
    id: 60,
    domain: "Domain 7 · Developer Productivity & Operational Enablement",
    select: 2,
    en: "Which TWO practices make Claude Code configuration safer for a team?",
    zh: "哪两项实践能让团队使用 Claude Code 更安全？（选择两项）",
    options: [
      ["Version shared project instructions, permissions, hooks, and approved MCP configuration.", "对共享项目指令、权限、hooks 和批准的 MCP 配置进行版本管理。"],
      ["Use least-privilege credentials and separate local, CI, and production identities.", "使用最小权限凭据，并隔离本地、CI 和生产身份。"],
      ["Share one administrator credential with the whole team.", "全团队共享一个管理员凭据。"],
      ["Allow every repository command without review.", "允许无需复核执行所有仓库命令。"],
    ],
    answer: [0, 1],
    rationaleEn: "Team enablement requires governed shared configuration and identity boundaries, not informal local setup.",
    rationaleZh: "团队赋能需要受治理的共享配置和身份边界，而不是非正式的个人设置。",
  },
  {
    id: 61,
    domain: "Domain 7 · Developer Productivity & Operational Enablement",
    select: 1,
    en: "What is the strongest rollout for an AI-assisted development workflow?",
    zh: "AI 辅助开发工作流最稳健的推广方式是什么？",
    options: [
      ["Enable it for every repository with no baseline.", "无基线地为所有仓库启用。"],
      ["Start with bounded tasks and volunteer teams, measure quality and cycle time, train reviewers, then expand with controls.", "从有边界任务和自愿团队开始，测量质量与周期，培训评审者，再带控制逐步扩大。"],
      ["Measure only prompt count.", "只测提示次数。"],
      ["Remove code review to maximize speed.", "移除代码评审以最大化速度。"],
    ],
    answer: [1],
    rationaleEn: "A staged rollout proves value and failure controls before organization-wide adoption.",
    rationaleZh: "分阶段推广能在组织级采用前证明价值和故障控制。",
  },
  {
    id: 62,
    domain: "Domain 7 · Developer Productivity & Operational Enablement",
    select: 1,
    en: "Developers report that Claude Code sometimes changes unrelated files. What is the best operational response?",
    zh: "开发者反馈 Claude Code 有时会修改无关文件。最佳运维响应是什么？",
    options: [
      ["Tell developers to trust the agent.", "让开发者相信代理。"],
      ["Reproduce with logs, narrow instructions and permissions, require diff review, add regression cases, and document recovery.", "通过日志复现，收窄指令和权限，强制 diff 评审，增加回归用例，并记录恢复方法。"],
      ["Disable version control.", "禁用版本控制。"],
      ["Grant broader filesystem access.", "授予更广文件系统权限。"],
    ],
    answer: [1],
    rationaleEn: "Operational resolution combines evidence, boundary reduction, verification, prevention, and recovery.",
    rationaleZh: "运维解决需要结合证据、缩小边界、验证、预防和恢复。",
  },
  {
    id: 63,
    domain: "Domain 7 · Developer Productivity & Operational Enablement",
    select: 2,
    en: "Which TWO measures best evaluate AI-assisted developer productivity?",
    zh: "哪两项指标最适合评估 AI 辅助开发生产力？（选择两项）",
    options: [
      ["Lead time, review time, rework, escaped defects, and successful task completion.", "交付周期、评审时间、返工、逃逸缺陷和任务成功率。"],
      ["Developer experience and adoption segmented by task type and team.", "按任务类型和团队细分的开发者体验与采用情况。"],
      ["Lines of generated code alone.", "只看生成代码行数。"],
      ["Number of model messages alone.", "只看模型消息数。"],
    ],
    answer: [0, 1],
    rationaleEn: "Productivity is an outcome system. Volume proxies can increase while quality and delivery performance worsen.",
    rationaleZh: "生产力是结果系统；生成量代理指标可能上升，但质量和交付表现反而下降。",
  },
];

export const officialSamplesMarkdown = renderQuestions(officialSampleQuestions);
export const claudePracticeBankMarkdown = renderQuestions(claudePracticeQuestions);
